// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWy-OuCFLRbhJ_y6Tjku5_APMi5RxMDkw',
    appId: '1:905878709786:web:23de3cb56a0d541cf653a3',
    messagingSenderId: '905878709786',
    projectId: 'obatku-c9d40',
    authDomain: 'obatku-c9d40.firebaseapp.com',
    storageBucket: 'obatku-c9d40.firebasestorage.app',
    measurementId: 'G-MBF47EEWXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcvq-gZTtws4UCxji3GIY0jqxrJ6cT0nk',
    appId: '1:905878709786:android:9d594f99b2e6308ef653a3',
    messagingSenderId: '905878709786',
    projectId: 'obatku-c9d40',
    storageBucket: 'obatku-c9d40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFDtMwA6Pi0ADNoQ-Di78g_q5CovFj9Tg',
    appId: '1:905878709786:ios:017711a1b8ca0357f653a3',
    messagingSenderId: '905878709786',
    projectId: 'obatku-c9d40',
    storageBucket: 'obatku-c9d40.firebasestorage.app',
    iosBundleId: 'com.example.obatku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFDtMwA6Pi0ADNoQ-Di78g_q5CovFj9Tg',
    appId: '1:905878709786:ios:017711a1b8ca0357f653a3',
    messagingSenderId: '905878709786',
    projectId: 'obatku-c9d40',
    storageBucket: 'obatku-c9d40.firebasestorage.app',
    iosBundleId: 'com.example.obatku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWy-OuCFLRbhJ_y6Tjku5_APMi5RxMDkw',
    appId: '1:905878709786:web:dd40fb3c21b20efdf653a3',
    messagingSenderId: '905878709786',
    projectId: 'obatku-c9d40',
    authDomain: 'obatku-c9d40.firebaseapp.com',
    storageBucket: 'obatku-c9d40.firebasestorage.app',
    measurementId: 'G-VYTFW6V75W',
  );
}
